package paintingsjdbc.service;

import static org.junit.Assert.assertEquals;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.ArrayList;
import java.util.List;

import paintingsjdbc.domain.Painting;
import paintingsjdbc.domain.Reproduktor;

public class Manager {
	
	private Connection connection;
	
	private String url= "jdbc:hsqldb:hsql://localhost/workdb";
	
	
	private String createTableReproductor = "CREATE TABLE IF NOT EXISTS Reproductor ("
			+ "idReproduktor INTEGER GENERATED BY DEFAULT AS IDENTITY, "
			+ "name VARCHAR(20), country VARCHAR(20), "
			+ "city VARCHAR(20), adress VARCHAR(50),"
			+ "house_number VARCHAR(7), telephone VARCHAR(50), "
			+ "e_mail VARCHAR(50),"
			+ "PRIMARY KEY(idReproduktor))";
	
	private String createTablePainting = "CREATE TABLE IF NOT EXISTS Painting"
			+ "(idPainting bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,"
			+ " name VARCHAR(20) NOT NULL,"
			+ " yoc INTEGER, cost INTEGER,"
			+ " artist VARCHAR(20), origin_artist VARCHAR(20),"
			+ " id_Reproduktor INTEGER FOREIGN KEY REFERENCES Reproductor(idReproduktor))";
	
	
	
	
	//C
	private PreparedStatement addReproductorStmt; //5  	1.1
	private PreparedStatement addPaintingStmt; //5		1.2

	//R
	private PreparedStatement getAllReproductorStmt; //2  	2.1
	private PreparedStatement getAllPaintingStmt; 	//		2.2

	private PreparedStatement getReproductorIdByNameStmt;//		3.1
	private PreparedStatement getFromReproduktorStmt; //3		3.2

	
	private PreparedStatement deleteReproductorFromPaintingStmt; // 4	4.1
	
	//U
	private PreparedStatement updateReproductorStmt;//		5.1
	private PreparedStatement updatePaintingStmt;//			5.2
	
	//D
	private PreparedStatement deleteReproductorStmt;//		6.1
	private PreparedStatement deletePaintingStmt;//			6.2
	

	// FK
	private PreparedStatement addReproductorToPaintingStmt;//	7.1
	
	
	
	private Statement statement;
	
	
	
	
	
	
	public Manager(){
		
		try {
			connection = DriverManager.getConnection(url);
			statement = connection.createStatement();
			
			ResultSet result = connection.getMetaData().getTables(null, null, null, null);
			boolean table = false;
			
			while (result.next()) {
				if ("Reproductor".equalsIgnoreCase(result.getString("TABLE_NAME"))) {
					table = true;
					break;
				}
			}
			
			if (!table) {
				
			statement.executeUpdate(createTableReproductor);
			}
			statement.executeUpdate(createTablePainting);
			
			// 1.1
			addReproductorStmt = connection.
					prepareStatement("INSERT INTO Reproductor ( name, country, city, adress, house_number, telephone, e_mail ) VALUES (?, ?, ?, ?, ?, ?, ?);");
			// 1.2
			addPaintingStmt = connection.
					prepareStatement("INSERT INTO Painting (name, yoc, cost, artist, origin_artist, id_Reproduktor) VALUES (?, ?, ?, ?, ?, ?);");
			
			
			// 2.1
			getAllReproductorStmt = connection.
					prepareStatement("SELECT * FROM Reproductor;");
			// 2.2
			getAllPaintingStmt = connection.
					prepareStatement("SELECT * FROM Painting;");
			
			// 3.1
			getReproductorIdByNameStmt = connection.
					prepareStatement("SELECT idReproduktor FROM Reproductor WHERE name = ? AND e_mail = ?;");
			// 3.2
			getFromReproduktorStmt = connection.
					prepareStatement("SELECT * FROM Painting WHERE id_Reproduktor = ?;");
			
			
			
			// 4.1
			deleteReproductorFromPaintingStmt = connection.
					prepareStatement("DELETE FROM Painting WHERE id_Reproduktor = ?;");
			
			
			
			// 5.1
			updateReproductorStmt = connection.
					prepareStatement("UPDATE Reproductor SET name = ?, country = ?, city = ?, adress = ?, house_number = ?, telephone = ?, e_mail = ?"
							+ "WHERE idReproduktor = ?;");
			// 5.2
			updatePaintingStmt = connection.
					prepareStatement("UPDATE Painting SET name = ?, yoc = ?, cost = ?, artist = ?, origin_artist = ?, id_Reproduktor = ? WHERE id_Reproduktor = ?;");
			
			
			// 6.1
			deleteReproductorStmt = connection.
					prepareStatement("DELETE FROM Reproductor WHERE idReproduktor = ?;");
			// 6.2
			deletePaintingStmt = connection.
					prepareStatement("DELETE FROM Painting WHERE id_Reproduktor = ?;");
			
			
			
			//7.1
			addReproductorToPaintingStmt = connection.
					prepareStatement("UPDATE Painting SET id_Reproduktor = ? WHERE idPainting = ?;");
			
			
		} catch (SQLException e) {
			// TODO: handle exception
			e.printStackTrace();
		}	
	}
	
	
	
	
	
	// 0 
	Connection getConnection() {
		return connection;
	}
	
	
	// 1.1
	public int addReproductor(Reproduktor reproduktor) {
		int counter = 0;
		
		
		try {
			
			addReproductorStmt.setString(1, reproduktor.getName());
			addReproductorStmt.setString(2, reproduktor.getCountry());
			addReproductorStmt.setString(3, reproduktor.getCity());
			addReproductorStmt.setString(4, reproduktor.getAdress());
			addReproductorStmt.setString(5, reproduktor.getHouse_number());
			addReproductorStmt.setString(6, reproduktor.getTelephone());
			addReproductorStmt.setString(7, reproduktor.getE_mail());
			
			
			counter = addReproductorStmt.executeUpdate();
			
		} catch (SQLException e) {
			// TODO: handle exception
			e.printStackTrace();
		}
		
		return counter;
	}
	
	// 1.2  ----
	public int addPainting(Painting painting, String name, String e_mail) {
		int counter = 0;
		
		try {
			
			
			
			connection.setAutoCommit(false);
			
			
			painting.setId(getReproductorIdByName(name, e_mail));
			
			
			addPaintingStmt.setString(1, painting.getName()); 
			addPaintingStmt.setInt(2, painting.getYoc());
			addPaintingStmt.setInt(3, painting.getCost());
			addPaintingStmt.setString(4, painting.getArtist());
			addPaintingStmt.setString(5, painting.getOrigin_artist());
			addPaintingStmt.setLong(6, painting.getId());
			
			System.out.println("AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAa");
			counter = addPaintingStmt.executeUpdate();
			System.out.println("aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa");
			connection.commit();
			
		} catch (SQLException e) {
			// TODO: handle exception
			e.printStackTrace();
			try {
				connection.rollback();
			} catch (SQLException e2) {
				// TODO: handle exception
				e2.printStackTrace();
			}
		}
		return counter;
	}
	
	
	
	// 2.1
	public List<Reproduktor> getAllReproductor() {
		List<Reproduktor> reproduktors = new ArrayList<Reproduktor>();
		
		try {
			ResultSet result = getAllReproductorStmt.executeQuery();
			
			while (result.next()) {
				Reproduktor r = new Reproduktor();
				r.setId(result.getLong("id"));
				r.setName(result.getString("name"));
				r.setCountry(result.getString("country"));
				r.setCity(result.getString("city"));
				r.setAdress(result.getString("adress"));
				r.setAdress(result.getString("house_number"));
				r.setTelephone(result.getString("telephone"));
				r.setE_mail(result.getString("e_mail"));
				reproduktors.add(r);
			}
		} catch (SQLException e) {
			// TODO: handle exception
			e.printStackTrace();
		}
		return reproduktors;
	}
	
	
	
	
	
	
	
	//3.1
	public long getReproductorIdByName(String name, String e_mail) {
		long r = 0;
		
		try {
			
			getReproductorIdByNameStmt.setString(1, name);
			getReproductorIdByNameStmt.setString(2, e_mail);
			
			ResultSet result = getReproductorIdByNameStmt.executeQuery(); ////
			
			result.next();
			r = result.getLong("idReproduktor"); 
			
			
		} catch (SQLException e) {
			// TODO: handle exception
			e.printStackTrace();
		}
		return r;
	}
	
	// 3.2
	public List<Painting> getFromReproduktor(Reproduktor reproduktor) {
		List<Painting> paintings = new ArrayList<Painting>();
		
		try {
			
			getFromReproduktorStmt.setLong(1, reproduktor.getId()); 
			
			ResultSet result = getFromReproduktorStmt.executeQuery();
			
			while (result.next()) {
				Painting painting = new Painting();
				
				painting.setId(result.getLong("id"));
				painting.setName(result.getString("name"));
				painting.setYoc(result.getInt("yoc"));
				
				painting.setArtist(result.getString("artist"));
				
				paintings.add(painting);
			}
			
		} catch (SQLException e) {
			// TODO: handle exception
			e.printStackTrace();
		}		
		return paintings;
	}

	
			
// TO PAINTING ??????????????????????????
// 4 -- deleteFromPainting                   NEAD TO ADD IN PAINTING      AND TRANSACTIONS !!!!!!!!!!!!!!!!!!!!!!!!!! 
	// 4.1
	public int deleteReproductorFromPaintin(Painting painting) {
		
		int counter = 0;
		try {
			deleteReproductorFromPaintingStmt.setLong(1, painting.getId()); // add method to find id painting in painting
			
			counter = deleteReproductorFromPaintingStmt.executeUpdate();
			
		} catch (SQLException e) {
			// TODO: handle exception
			e.printStackTrace();
		}
		
		return counter;
	}

	
			
		
		
		
		
		
		
		
	// 5.1
	public int updateReproductor(Reproduktor reproduktorOld, Reproduktor reproduktorNew) {
		
		int counter = 0;
		try {
			connection.setAutoCommit(false);
			
			updateReproductorStmt.setString(1, reproduktorNew.getName());
			updateReproductorStmt.setString(2, reproduktorNew.getCountry());
			updateReproductorStmt.setString(3, reproduktorNew.getCity());
			updateReproductorStmt.setString(4, reproduktorNew.getAdress());
			updateReproductorStmt.setString(5, reproduktorNew.getHouse_number());
			updateReproductorStmt.setString(6, reproduktorNew.getTelephone());
			updateReproductorStmt.setString(7, reproduktorNew.getE_mail());
			
			updateReproductorStmt.setLong(8, getReproductorIdByName(reproduktorOld.getName(), reproduktorOld.getE_mail()));
			
			counter = updateReproductorStmt.executeUpdate();
			connection.commit();
			
		} catch (SQLException e) {
			// TODO: handle exception
			e.printStackTrace();
			try {
				connection.rollback();
			} catch (SQLException e2) {
				// TODO: handle exception
				e2.printStackTrace();
			}
		}
		return counter;
	}
	
	
	
	//7.1
	public int addReproductorToPainting(long idReproduktor, long idPainting) {
		int count = 0;
		
		try {
			
			addReproductorToPaintingStmt.setLong(1, idReproduktor);
			addReproductorToPaintingStmt.setLong(2, idPainting); 
			
			count = addReproductorToPaintingStmt.executeUpdate();
			
		} catch (SQLException e) {
			// TODO: handle exception
			e.printStackTrace();
		}		
		
		return count;
	}
		
		
		
		
			
			
			
			
			
			
			
			
			
			
			/*
			// 2 - getAllPainting
			public List<Painting> getAllPainting() {
				
				List<Painting> paintings = new ArrayList<Painting>();
				
				try {
					ResultSet result = getAllPaintingStmt.executeQuery();
					
					while (result.next()) {
						Painting painting = new Painting();
						
						painting.setId(result.getLong("id"));
						painting.setName(result.getString("name"));
						painting.setYoc(result.getInt("yoc"));
						painting.setArtist(result.getString("artist"));
						
						paintings.add(painting);
					}

				} catch (SQLException e) {
					// TODO: handle exception
					e.printStackTrace();
				}
				return paintings;
			}		
			*/
			
			// 3 - 
			
			
			
			
			
			/*
			// 4 - deleteFromReproductor
			public void deleteFromReproductor(Reproduktor reproductor) {
				
				try {
					deleteFromReproductorStmt.setLong(1, reproductor.getId()); // 3 - 1
					
					deleteFromReproductorStmt.executeQuery();
					
				} catch (SQLException e) {
					// TODO: handle exception
					e.printStackTrace();
				}
			}
			*/
			
			
			/*
			//6
			public void updatePainting(long id, Painting painting) {
				
				try {
					
					updatePaintingStmt.setString(1, painting.getName());
					updatePaintingStmt.setInt(2, painting.getYoc());
					updatePaintingStmt.setString(3, painting.getArtist());
					updatePaintingStmt.setLong(4, id);
					
					updatePaintingStmt.executeUpdate();
					
				} catch (SQLException e) {
					// TODO: handle exception
					e.printStackTrace();
				}
			}
			*/
			
			
			
	
	
	
	

}
