package paintingsjdbc.service;

import java.sql.Connection;

public class PaintingManager {

	private Connection connection;

	private String url = "jdbc:hsqldb:hsql://localhost/workdb";
	
	private String createTablePainting = "CREATE TABLE Painting(id bigint GENERATED BY DEFAULT AS IDENTITY, name varchar(20) NOT NULL, yoc INTEGER, idReproduktor INTEGER NOT NULL REFERENCES Reproduktor(id))";
	

}
